apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: kfy26a2zn-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/kfy26a2zn-dotnet-basic-gitops